<div class="col-sm-6 col-md-4">
<div class="thumbnail">
    <a href="<?=$this->baseUrl('image/view')?>"><img data-src="holder.js/300x200" alt="..."></a>
  <div class="caption">
    <p><?=$this->description?></p>
    <?php if($this->controls){ ?>
    <p><a href="#" class="btn btn-default" role="button"><?=$this->translate('remove')?></a>
        <a href="#" class="btn btn-default" role="button"><?=$this->translate('edit_privacy')?></a></p>
    <?php } ?>
  </div>
</div>
</div>