<h1><?=$this->translate('add_image')?></h1>
<form class="form-horizontal" role="form" action="<?=$this->baseUrl('image/postimage')?>" method="POST">
  <div class="form-group">
    <label for="inputFile" class="col-md-2 control-label"><?=$this->translate('image_file')?></label>
    <div class="col-md-10">
        <input type="file" class="form-control" id="inputFile" name="image" placeholder="<?=$this->translate('file')?>">
    </div>
  </div>
  <div class="form-group">
    <label for="inputDesc" class="col-md-2 control-label"><?=$this->translate('description')?></label>
    <div class="col-md-10">
      <input type="text" class="form-control" id="inputDesc" name="description" placeholder="<?=$this->translate('description')?>">
    </div>
  </div>
  <div class="form-group">
    <div class="col-md-offset-2 col-md-10">
      <button type="submit" class="btn btn-default"><?=$this->translate('add_image')?></button>
    </div>
  </div>
</form>