<?php 
$rating = round($this->image["photo"]->rating_count > 0 ? $this->image["photo"]->rating_sum / $this->image["photo"]->rating_count : 0);
?>
<img src="<?=$this->baseUrl('image/get/file/'.$this->image["photo"]->file_id.'/size/800x600')?>" alt="..." />
<div id="dsc" class="panel panel-default"><?=$this->image["photo"]->description?></div>
<div class="panel"><?=$this->translate('added_by')?> <a href="<?=$this->baseUrl('list/user/username/'.$this->image["user"]->username)?>"><?=$this->image["user"]->username?></a></div>
<div class="panel">
    <?php foreach($this->image["tags"] as $tagId => $tagName){?>
    <a href="list/tag/id/<?=$tagId?>"><?=$tagName?></a>
    <?php }?>
</div>

<div class="panel">
<?php if($this->isLoggedIn){ ?>
    <input type="number" name="rate" id="rating_element" class="rating" value="<?=$rating?>" disabled />
<?php } else {
    echo str_repeat("<i class='glyphicon glyphicon-star'></i>", $rating);
    echo str_repeat("<i class='glyphicon glyphicon-star-empty'></i>",6-$rating);
}
?>
    
</div>
<?php foreach($this->image["comments"] as $comment){ ?>
<div class="panel panel-primary">
    <div class="panel-heading"><a style="color:white" href="<?=$this->baseUrl('list/user/username/'.$comment["username"])?>"><?=$comment["username"]?></a> @ <?=date("d.m.Y H:i",strtotime($comment["comment_added"]))?></div>
  <div class="panel-body">
    <?=$comment["comment"]?>
  </div>
</div>
<?php } ?>
<form class="form-horizontal" role="form" action="<?=$this->baseUrl('image/comment')?>" method="POST">
<input type="hidden" name="file" value="<?=$this->image["photo"]->file_id?>" />
<input type="hidden" name="returnPath" value="image/view/id/<?=$this->image["photo"]->short_url_id?>" />
<div>
  <div class="input-group">
    <input type="text" class="form-control" name="comment" <?=($this->isLoggedIn?'':'disabled')?> required>
    <span class="input-group-btn">
        
      <button class="btn btn-default" type="submit" <?=($this->isLoggedIn?'':'disabled')?> ><?=$this->translate('comment')?> <span class ="glyphicon glyphicon-comment"></span></button>
    </span>
  </div>
</div>
</form>
<script type="text/javascript">
    $("#rating_element").change(function(){
        $.get('<?=$this->baseUrl('image/rate/file/'.$this->image["photo"]->file_id.'/rating/')?>'+$(this).val());
    });
</script>