<img data-src="holder.js/800x800" alt="..." />
<div id="dsc" class="panel panel-default">Kuvaus kommer här</div>

<div class="panel">
    <a href="<?=$this->baseUrl('list/tag')?>">tag1</a>
    <a href="<?=$this->baseUrl('list/tag')?>">tag2</a>
    <a href="<?=$this->baseUrl('list/tag')?>">tag3</a>
    <a href="<?=$this->baseUrl('list/tag')?>">tag4</a>
</div>

<div class="panel">
    <input type="number" name="rate" id="some_id" class="rating" />
</div>

<div class="panel panel-primary">
  <div class="panel-heading">Teppoperusjäbä</div>
  <div class="panel-body">
    Hieno kuva hermanni
  </div>
</div>
<div class="panel panel-primary">
  <div class="panel-heading">Teppoperusjäbä</div>
  <div class="panel-body">
    Ei ookkaan
  </div>
</div>
<div>
  <div class="input-group">
    <input type="text" class="form-control">
    <span class="input-group-btn">
        
      <button class="btn btn-default" type="button"><?=$this->translate('comment')?> <span class ="glyphicon glyphicon-comment"></span></button>
    </span>
  </div>
</div>

