<h1><?=$this->translate('login')?></h1>
<?php if($this->error){ ?>
<div class="alert alert-danger"><?=$this->translate('invalid_username_or_password')?></div>
<?php
} 
?>
<form class="form-horizontal" role="form" action="<?=$this->baseUrl('auth/authenticate')?>" method="POST">
  <div class="form-group">
    <label for="inputUsername1" class="col-md-2 control-label"><?=$this->translate('username')?></label>
    <div class="col-md-10">
      <input type="text" class="form-control" id="inputUsername1" name="username" placeholder="<?=$this->translate('username')?>">
    </div>
  </div>
  <div class="form-group">
    <label for="inputPassword1" class="col-md-2 control-label"><?=$this->translate('password')?></label>
    <div class="col-md-10">
      <input type="password" class="form-control" id="inputPassword1" name="password" placeholder="<?=$this->translate('password')?>">
    </div>
  </div>
  <div class="form-group">
    <div class="col-md-offset-2 col-md-10">
      <button type="submit" class="btn btn-default"><?=$this->translate('login')?></button>
    </div>
  </div>
</form>